# pull base slc6 image
FROM cern/slc6-base
# expose port 8443
#EXPOSE 8443
# expose port 80 for tomcat6
#EXPOSE 80
# set hostname
#ENV hostname docker-vm-cc7.cern.ch
# copy host certificate to /etc/grid-security
